substitutions:
  _HUGO_VERSION: "0.79.1"
  _MIRROR_CLOUD_REPO: "github_mrraz_techdoc"

images: 
  - 'gcr.io/$PROJECT_ID/hugo-${_HUGO_VERSION}:latest'
  
# https://cloud.google.com/cloud-build/docs/build-config
# This ste

steps:

# this step is needed due to issue with cloud build not downloading git submodule documented in (https://stackoverflow.com/questions/59180893/google-cloud-build-cant-update-submodules) 

- id: 'download git submodule'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git config -f .git/config submodule.${_MIRROR_CLOUD_REPO}.url https://source.cloud.google.com/$PROJECT_ID/${_MIRROR_CLOUD_REPO} 
      git config -f .gitmodules submodule.${_MIRROR_CLOUD_REPO}.url https://source.cloud.google.com/$PROJECT_ID/${_MIRROR_CLOUD_REPO}
      git submodule init
      git submodule update --init --recursive


# the step needed only only when creating/updating Hugo image from docker file
- id: 'build hugo image'
  name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '--build-arg', 'HUGO_VERSION=${_HUGO_VERSION}',
            '-t', 'gcr.io/$PROJECT_ID/hugo-${_HUGO_VERSION}:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/hugo-${_HUGO_VERSION}:latest',
            '-f', 'hugo.Dockerfile', 'content/'
        ]
# This step installs npm dependencies/requirement based on package.jason file and runs hugo build to generate static pages on ./public/pub directory
- id: 'hugo build site'
  name: 'gcr.io/$PROJECT_ID/hugo-${_HUGO_VERSION}:latest'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      npm install 
      hugo -d ./public/public

# This step deploys static pages from ./public/public folder into app engine. 
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'cp app.yaml ./public/app.yaml && cd public && gcloud app deploy app.yaml']


options:
  machineType: 'N1_HIGHCPU_32'

timeout: '1600s'